name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Install and Build
      run: |
        yarn install
        yarn run build -- --prefix-paths

    - name: Deploy
      uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.GATSBY }}
        deploy-branch: gh-pages
        gatsby-args: --prefix-paths