name: Build and Zip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Zip public directory
      run: |
        zip -r public.zip public/
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: public.zip
        path: public.zip
